name: "Deploy to AWS S3"
description: "Deploy a static website to AWS S3"
inputs:
  bucket:
    description: "The name of the bucket to deploy to"
    required: true
  bucket-region:
    description: "The region of the bucket to deploy to"
    required: false
    default: "eu-west-1"
runs:
  using: "node16"
  main: "main.js"
